# NuGet restore
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY *.sln .
COPY TestProject.Api/*.csproj TestProject.Api/
RUN dotnet restore
COPY . .

# publish
FROM build AS publish
WORKDIR /src/TestProject.Api
RUN dotnet publish -c Release -o /src/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=publish /app/TestProject.Api/src/publish .
# ENTRYPOINT ["dotnet", "TestProject.Api.dll"]
# heroku uses the following
CMD ASPNETCORE_URLS=http://*:$PORT dotnet TestProject.Api.dll
